language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get install autoconf automake libtool autotools-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 libstdc++-4.8-dev
  - sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60
    --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
    --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8
  - sudo update-alternatives --quiet --set gcc /usr/bin/gcc-4.8
  - curl -O https://capnproto.org/capnproto-c++-0.4.1.tar.gz
  - tar zxf capnproto-c++-0.4.1.tar.gz
  - cd capnproto-c++-0.4.1
  - ./configure
  - make check
  - sudo make install
  - cd ..
  - wget http://download.nanomsg.org/nanomsg-0.3-beta.tar.gz
  - tar -xvzf nanomsg-0.3-beta.tar.gz
  - cd nanomsg-0.3-beta && ./configure && make && sudo make install
  - cd ..
  - sudo ldconfig
install:
  - pip install cython
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - bash scripts/run_tests.sh
